version: '3.7'

services:
  users_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/mysql1/data
  posts_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=users
    ports:
      - "5434:5434"
    expose:
      - "5434"
    volumes:
      - pgdata:/var/lib/mysql2/data

  users:
    image: epamjuanpablofernandezmontojo/userservice
    environment:
      - DB_URL=jdbc:mysql://posts_db:3308/users
      - DB_USERNAME=admin
      - DB_PASSWORD=admin1234
    ports:
      - "8082:8082"
    depends_on:
      - users_db
  posts:
    image: epamjuanpablofernandezmontojo/postservice
    environment:
      - DB_URL=jdbc:mysql://posts_db:3309/posts
      - DB_USERNAME=admin
      - DB_PASSWORD=admin1234
    ports:
      - "8080:8080"
    depends_on:
      - posts_db
volumes:
  pgdata: