version: '3.7'

services:
  users_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=users
    ports:
      - "3308:3306"
    volumes:
      - pgdata:/var/lib/mysql1/data

  posts_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=posts
    ports:
      - "3309:3306"
    volumes:
      - pgdata:/var/lib/mysql2/data

  usersapp:
    image: epamjuanpablofernandezmontojo/userservice
    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3308/users?useSSL=false
      - DB_URL=jdbc:postgresql://users_db:5432/users
      - DB_USERNAME=admin
      - DB_PASSWORD=admin1234
    ports:
      - "8082:8082"
    depends_on:
      - users_db
#    restart: always

  postsapp:
    image: epamjuanpablofernandezmontojo/postservice
    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3309/posts?useSSL=false
      - DB_URL=jdbc:postgresql://posts_db:5432/posts
      - DB_USERNAME=admin
      - DB_PASSWORD=admin1234
    ports:
      - "8080:8080"
    depends_on:
      - posts_db

volumes:
  pgdata:

#networks:
#  postsnetwork:
#  usersnetwork:
#  services: