version: '3.7'

services:
  users_db:
    image: mysql:8.0.30
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin1234
      - MYSQL_ROOT_PASSWORD=admin1234
      - MYSQL_DATABASE=users
    networks:
      - usersnetwork
    ports:
      - "3308:3306"
    volumes:
      - pgdata:/var/lib/mysql1/data

  posts_db:
    image: mysql:8.0.30
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin1234
      - MYSQL_ROOT_PASSWORD=admin1234
      - MYSQL_DATABASE=posts
    networks:
      - postsnetwork
    ports:
      - "3309:3306"
    volumes:
      - pgdata:/var/lib/mysql2/data

  usersapp:
    image: epamjuanpablofernandezmontojo/userservice
    environment:
      - DB_URL=jdbc:mysql://users_db:3308/users?useSSL=false
      - DB_USERNAME=admin
      - DB_PASSWORD=admin1234
    ports:
      - "8082:8082"
    depends_on:
      - users_db
    networks:
      - usersnetwork
      - services

  postsapp:
    image: epamjuanpablofernandezmontojo/postservice
    environment:
      - DB_URL=jdbc:mysql://posts_db:3309/posts?useSSL=false
      - DB_USERNAME=admin
      - DB_PASSWORD=admin1234
    ports:
      - "8080:8080"
    depends_on:
      - posts_db
    networks:
      - postsnetwork
      - services

volumes:
  pgdata:

networks:
  postsnetwork:
  usersnetwork:
  services: